### ISSUE TITLE
Time to retire cerbere?

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/cerbere#36]
While looking into the various polkit issues reported recently, I've found that it's probably something related to things like #35 or #33 . It seems cerbere clings on (despite being told to exit), even at logout and leaves behind a mess that the next session can't quite clean up and recover from.

I've tried digging into the cause of these issues a bit further and I'm making very slow progress due to the difficulty in debugging Cerbere.

I've already ran a little experiment that proves it would be possible to have `gnome-session` launch and relaunch (in the case of failure) components that are currently looked after by cerbere (plank and wingpanel), but there are a couple of points to consider:

* There's a hardcoded restart limit within `gnome-session` wherein if something crashes or is killed more than once within a minute, it's considered dead.
* If this crashing/killed component is listed as a required component of the session, then the session is considered dead too and you get kicked back to the login screen.

So there's a decision to be made as to whether wingpanel and/or plank should be considered required components of the session. It feels as though if wingpanel is failing to start, then it would make sense to drop out of the session as pantheon isn't much use without wingpanel. However, I feel as though crashing more than once within a minute being considered a failure is a bit aggressive.

The immediate concern for me is that the above makes developing wingpanel (or indicators) hard because if you restart wingpanel more than once within a minute (which I frequently do while working on wingpanel), then you kill your session.

However, if we don't list plank and wingpanel as required components of the session, then they should be restarted as long as they're not crashing more than once every minute. If the limit is breached, then the automatic restarting stops and you're left in a session without wingpanel and/or plank.

I suppose another option would be to leave them as required components but patch `gnome-session` to make this limit less aggressive.

I think the controllability of these limits improves slightly in GNOME >3.34 as I believe they're using systemd to manage session components now instead of custom code within `gnome-session`. But I think even migrating to using `gnome-session` at this point could still be worthwhile as it's slightly closer to the current/future GNOME philosophy and it's probably a quick way to clean up a few of the bugs we're seeing related to cerbere.

Thoughts?

**Comment by danirabbit** [comment]
I think moving to using GNOME Session without the `required` option is probably going to give us the most similar outcome to the current behavior. Cerbere stops trying to restart the component after some limit that's less agressive, but realistically if we're seeing some kind of crashing in shell components that frequently that seems like a bigger issue.

I think I agree with you that leaving off the `required` option is probably better for development since getting kicked out the session while working on the panel would be a pain.

Maybe can re-investigate having a developer session or something in the future so that we can give users this extra protection of exiting the session. But I would consider that outside the scope of the current issue.

I'm in favor of retiring cerbere and using GNOME session here :)

**Comment by tintou** [comment]
I'm also in favor of retiring cerbere and using GNOME Session without the `required` field as it is not a core component like Gala would be for instance.

**Comment by davidmhewitt** [comment]
Further experiments with this show that wingpanel is happy being launched and managed by `gnome-session` in this way, but plank fails to start for some reason and I can't find a single reason why in the logs.

Continuing to investigate...

**Comment by davidmhewitt** [comment]
Ok, figured that out, there was a `NotShowIn=Pantheon;` in the plank desktop file that was telling `gnome-session` not to start it. I now have a session where plank and wingpanel are launched by `gnome-session` and aren't required components. Cerbere isn't running and doesn't need to run anymore and I don't seem to be having issues with polkit anymore.

However, they're not automatically restarted when they crash or are killed. I think we need to add some extra code to wingpanel and plank so they register with the session manager properly. I'll test this out next.

**Comment by davidmhewitt** [comment]
Not as complicated as I thought, I'd just typo'd something. It's just changes to some install paths and desktop files to replace cerbere with `gnome-session` and make polkit work again...

In summary, we need to ensure the following are set in the desktop files for wingpanel and plank and ensure we remove any `NotShowIn=Pantheon` keys:
```
NoDisplay=true
X-GNOME-Autostart-Notify=false
X-GNOME-AutoRestart=true
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Phase=Panel
OnlyShowIn=Pantheon;
```

We also need to install those desktop files to `/etc/xdg/autostart` and we need to disable cerbere in some way, which is as simple as removing its autostart file from the same folder, or maybe removing plank and wingpanel from it's config of watched applications.

When these fixes are released to users, there will obviously need to be a simultaneous plank, cerbere and wingpanel release.

There are reasons why I haven't just gone ahead and done PRs for that:
* There's a desktop file specific to elementary/pantheon for plank that I can't find in a repository anywhere. It appears at some point in launchpad as a patch, but I can't track down the source, so :man_shrugging: 
* I'm not sure of the best way to disable cerbere, I guess we need to make a new release that's essentially an empty package to sunset it for current users, but unsure if that's correct?
* Also unsure how these changes to desktop files and installing them into the autostart folder affects other distros and their packaging.

I don't have a huge amount of time at the moment to look into the above as I'm really busy with my day job, but hopefully this investigation helps and provides some relatively bite sized tasks for someone else to pick up and finish off the fix.

**Comment by danirabbit** [comment]
Wingpanel autostart desktop added in https://github.com/elementary/wingpanel/pull/274

**Comment by quequotion** [comment]
I like this idea, but I am not sure that it works. I could not find much in the way of documentation regarding `X-GNOME-AutoRestart` (GNOME's own wiki only briefly mentions it with a [dead link](https://wiki.gnome.org/Projects/SessionManagement/GnomeSession#A8._Termination)).

I tried it out myself with [Pantheon 3D](https://www.youtube.com/watch?v=iDO8TsI3eZ4&list=PLYkgvMpJJEaIOF5pDFk50eCPWYtkN70yC).

I have this gnome-session file (no cerbere, wingpanel, or plank in `RequiredComponents`):

```
[GNOME Session]
Name=Pantheon
RequiredComponents=compiz;
FallbackSession=gnome-shell
DesktopNames=Pantheon
```

Rather than doubling up on .desktop files, I edited the main ones and symlinked them to `/etc/xdg/autostart/` (I also tried independent files, but there was no difference):

`io.elementary.wingpanel.desktop` (translation entries edited out for brevity):

```
[Desktop Entry]
Name=Wingpanel
Comment=Top panel that holds indicators and the applications menu
Exec=wingpanel
Icon=io.elementary.wingpanel
Terminal=false
Type=Application
Categories=Utility;
NoDisplay=true
X-Ubuntu-Gettext-Domain=wingpanel
X-GNOME-Autostart-Notify=false
X-GNOME-AutoRestart=true
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Phase=Panel
OnlyShowIn=Pantheon;
```

`plank.desktop` (translation entries edited out for brevity):

```
[Desktop Entry]
Name=Plank
GenericName=Dock
Comment=Stupidly simple.
Categories=Utility;
Type=Application
Exec=plank
Icon=plank
Terminal=false
NoDisplay=false
X-GNOME-Autostart-Notify=false
X-GNOME-AutoRestart=true
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Phase=Panel
OnlyShowIn=Pantheon;
```

Both start at login, as expected, but do not restart if I kill them. Is the problem that they are killed, not crashed? Does gnome-session know the difference? is something missing? or does `X-GNOME-AutoRestart` not work?

Note: If it is broken, I'm all for going upstream and getting it fixed so that this can work.

**Comment by davidmhewitt** [comment]
I can say that they definitely restart when killed for me using this method. Are you using the same version of `gnome-session` as what would be available in elementary 5.1?

Additionally you could add `--debug` to the flags passed to `gnome-session` in your `xsession` file and have a look what your journal says.

But considering a couple of people in the elementary team have tested this method and found that it starts and restarts now, I think this is an issue at your end.

**Comment by quequotion** [comment]
I have gnome-session 3.34.2-1 from Archlinux's [extra] repository. Arch usually has a newer version of things than Ubuntu, but I do not know which version is provided with Hera.

EDIT: I was doing it wrong; `--debug` works.

**Comment by davidmhewitt** [comment]
`gnome-session` >= 3.34 starts using systemd for starting and restarting session components I believe. I'm not sure if the restart keys in the desktop file are fully deprecated and don't work by that point. But there's certainly an alternative that GNOME is using in that version.

I'm going to mark these comments as off topic as issues with a different version of gnome session to what we're using are outside the scope of this.

**Comment by quequotion** [comment]
> `gnome-session` >= 3.34 starts using systemd for starting and restarting session components I believe. I'm not sure if the restart keys in the desktop file are fully deprecated and don't work by that point. But there's certainly an alternative that GNOME is using in that version.

It may use systemd for session components, but it should still honor xdg autostart .desktop files (technically, _not_ session components).

I couldn't get any output from gnome-session --debug when killing plank or wingpanel, but it does output this just at login, when it first initiates them:

```
Jan 13 18:08:23 localhost gnome-session-binary[2708]: WARNING: Application 'plank.desktop' failed to register before timeout
Jan 13 18:08:23 localhost gnome-session-binary[2708]: WARNING: Application 'io.elementary.wingpanel.desktop' failed to register before timeout
```

> I'm going to mark these comments as off topic as issues with a different version of gnome session to what we're using are outside the scope of this.

I understand, still, worth discussing if it means elementary will have to change direction again in a few months (hopefully it does not; seems like there's probably something that can be done).

~~Edit: I added `StartupNotify=true` and changed `X-GNOME-Autostart-Notify` to `true` as well, which got rid of the warnings~~, but didn't fix the lack of autorestart.

Edit again: only worked for one boot; warnings came back.

It is not unlike GNOME to quietly drop a feature they don't think many people use, especially when they have a shiny new plan to replace it. 

It may be less work to set up (user) systemd services now than having to undo the xdg autostart effort and make systemd services anyway later.

**Comment by davidmhewitt** [comment]
> It may use systemd for session components, but it should still honor xdg autostart .desktop files (technically, _not_ session components).

It sounds like it does still honor the XDG autostart, just not the `X-GNOME-AutoRestart=true`, which is obviously a GNOME specific extension anyway.

> I couldn't get any output from gnome-session --debug when killing plank or wingpanel, but it does output this just at login, when it first initiates them:
> 
> ```
> Jan 13 18:08:23 localhost gnome-session-binary[2708]: WARNING: Application 'plank.desktop' failed to register before timeout
> Jan 13 18:08:23 localhost gnome-session-binary[2708]: WARNING: Application 'io.elementary.wingpanel.desktop' failed to register before timeout
> ```

Yes, currently wingpanel and plank do not register with the session manager and would require extra code in each to do so. However, this does not seem to be a requirement for the automatic restarting, at least with our version of GNOME session (3.28).


> I understand, still, worth discussing if it means elementary will have to change direction again in a few months (hopefully it does not; seems like there's probably something that can be done).

Definitely worth discussing, and apologies if I came across as abrupt or dismissive. We're trying to pursue this as a quick fix to a number of quite major problems in the currently released version of elementary cause by cerbere so thinking about how this might work in the future is a low priority. However, I did say I was unsure how this would affect other distros, so this is useful information and we'd certainly be interested to hear your findings and any solutions you find.

**Comment by quequotion** [comment]
> Definitely worth discussing, and apologies if I came across as abrupt or dismissive. We're trying to pursue this as a quick fix to a number of quite major problems in the currently released version of elementary cause by cerbere so thinking about how this might work in the future is a low priority. However, I did say I was unsure how this would affect other distros, so this is useful information and we'd certainly be interested to hear your findings and any solutions you find.

No worries; I'll keep digging. It does sound like this is likely to require (a) separate issue report(s), toward the eventual implementation of user systemd services for wingpanel and plank (as much as I'd rather not dictate use of systemd.. the facts are that I am already using it and so is every elementary OS user). 

Edit: [I found a workaround](https://www.reddit.com/r/gnome/comments/eo9mgb/was_xgnomeautorestart_deprecated/fedyzlb/). In order to use X-GNOME-AutoRestart with gnome-session 3.34+, it is necessary to start gnome-session with `--builtin`, and avoid systemd session management altogether!

**Comment by MamasLT** [comment]
Guys, please! This 1 minute 29 seconds wait time every time we Restart/Shut Down the Elementary OS is absurd. And most of us don't want or have knowledge how to fix all this manually. Honestly I think it looks really bad from developers side not to fix this issue for so long.
There are multiple forums and comments online, hundreds of people complaining and asking for a solution from Elementary Team...

UPDATE: I just tried killing cerbere process before rebooting, and reboot worked like a charm! So clearly that process is what is causing this issue. Do we really need it?

Thank you.

**Comment by danirabbit** [comment]
Closing since this should now be completed
